Ui/sidebar scope fix2
teambit/bit pull request #3244
Opened 2020-10-20 14:25 UTC by odedre

## Proposed Changes

remove sidebar scope component when in scope - method 2 - drawer now getting TreeNode from outside

2020-10-21 16:12 UTC, KutnerUri requested changes

2020-10-21 16:12 UTC, KutnerUri commented on components/side-bar/component-tree/component-nodes/component-nodes.tsx
> -        <div style={indentStyle(depth + 2)} className={classNames(styles.componentTree)}>
so you gave up on the double indent?

2020-10-21 16:12 UTC, KutnerUri commented on components/side-bar/component-tree/index.ts
> +export { ScopeView, NamespaceView } from './component-nodes';
plz split. What do you think about ScopeTreeNode and NamespaceTreeNode?

2020-10-21 16:12 UTC, KutnerUri commented on components/side-bar/index.ts
> +export { ComponentView, ScopeView, NamespaceView, PayloadType, TreeNodeProps, ScopePayload } from './component-tree';
merge exports

2020-10-21 16:12 UTC, KutnerUri commented on extensions/component-tree/component-tree.drawer.tsx
> +// import { useComponentHost } from '@teambit/component';
is this supposed to be commented out?

2020-10-21 16:12 UTC, KutnerUri commented on extensions/scope/components.drawer.tsx
> +        // skip over scope node and render only children
👍

2020-10-22 14:04 UTC, KutnerUri commented
looks good!

2020-10-22 14:04 UTC, KutnerUri approved these changes
looks good

2020-10-22 14:34 UTC, guysaar223 approved these changes

2020-10-22 14:34 UTC, merged