Ui/key bindings
teambit/bit pull request #3314
Opened 2020-11-02 16:46 UTC by odedre

## Proposed Changes

- added new key bindings
- added key bindings to component menu

2020-11-05 12:10 UTC, KutnerUri requested changes

2020-11-05 12:10 UTC, KutnerUri commented on scopes/ui-foundation/uis/main-dropdown/main-dropdown.tsx
> +          <KeyCombo>{keyChar}</KeyCombo>
please use `<KeySequence>` (= combo + sequence)

2020-11-05 12:10 UTC, KutnerUri commented on scopes/workspace/workspace/workspace.ui.runtime.tsx
> -  private registerExplicitRoutes() {
where is this??

2020-11-05 12:10 UTC, KutnerUri commented on scopes/scope/scope/scope.ui.runtime.tsx
> +  private setKeyBindHandler: (updated: CommandHandler) => void = () => {};
let's talk about this again

2020-11-05 12:14 UTC, odedre commented on scopes/workspace/workspace/workspace.ui.runtime.tsx
> -  private registerExplicitRoutes() {
moved to the provider like ran asked

2020-11-05 13:14 UTC, KutnerUri commented
also consider - 

* rename ui.main-dropdown -> ellipsis-dropdown / harmburger-dropdown
* remove unused command-bar-context

2020-11-08 13:22 UTC, KutnerUri requested changes

2020-11-08 13:22 UTC, KutnerUri commented on scopes/component/component/component.ui.runtime.tsx
> +      id: 'copyBitId', // TODO - extract to a component!
1. prefix with `'component.'`
1. extract to constant! you can move it to another file in this same component

2020-11-08 13:22 UTC, KutnerUri commented on scopes/component/component/component.ui.runtime.tsx
> +      id: 'copyNpmId', // TODO - extract to a component!
same

2020-11-08 16:40 UTC, KutnerUri approved these changes

2020-11-08 18:04 UTC, merged