New tooltips
teambit/bit pull request #3735
Opened 2021-02-03 19:16 UTC by KutnerUri

## Proposed Changes

- Use glorified `@tippy.js/react` for tooltips
- New design, Redigma approved
- Replace react-tooltip with new tooltip.
- Add mount point to place all tooltips outside the normal flow (so they won't get affected by scaling, links, etc)

![great success](https://media.giphy.com/media/1eEH72j9Cd0VEFosRf/giphy.gif)

2021-02-04 11:04 UTC, odedre requested changes

2021-02-04 11:04 UTC, odedre commented on workspace.jsonc
>          "unist-util-remove": "2.0.1",
remove `react-tooltip` if its not used anymore

2021-02-04 18:38 UTC, KutnerUri commented on scopes/component/ui/component-tooltip/component-tooltip.tsx
> +  if (!status) return children;
No: children are the target for the tooltip (`N`, `M`, etc), and not its content.
Returning them without the tooltip will just render them without the tooltip.

2021-02-04 18:38 UTC, KutnerUri commented on scopes/design/ui/tooltip/index.ts
> +export { UseSingletonProps } from '@tippyjs/react';
idk. Let's talk about it.

2021-02-04 18:39 UTC, KutnerUri commented on scopes/design/ui/tooltip/tooltip.scss
> +$bg: #2b2b2b;
I will update!

2021-02-04 18:43 UTC, KutnerUri commented on scopes/design/ui/tooltip/tooltip.scss
> +$bg: #2b2b2b;
Not sure it's the right use case though: it's a certain type background.
Actually, I could apply [dark-theme](https://bit.dev/teambit/base-ui/theme/dark-theme) on it. 🤔 
That would also make any components we may put inside of it (like buttons) dark.

2021-02-04 18:44 UTC, KutnerUri commented on scopes/design/ui/tooltip/tooltip.tsx
> +import './tooltip.scss';
The vanilla component is Tippy itself.
It's using html attribute to style theme, so it's global.

2021-02-04 18:45 UTC, KutnerUri commented on scopes/design/ui/tooltip/tooltip.tsx
> +    <Tippy arrow={roundArrow} theme={THEME} interactive appendTo={getMountPoint} {...props} singleton={singleton}>
yes, both are overridable!

2021-02-04 18:45 UTC, KutnerUri commented on scopes/envs/ui/env-icon/env-icon.tsx
> +export const EnvIcon = forwardRef<HTMLImageElement, EnvIconProps>(function EnvIcon(
so eslint would not say I'm using anonymous components.

2021-02-07 14:53 UTC, KutnerUri commented on scopes/envs/ui/env-icon/env-icon.tsx
> +export const EnvIcon = forwardRef<HTMLImageElement, EnvIconProps>(function EnvIcon(
yes apparently JS/TS is cool with it

2021-02-07 18:12 UTC, odedre approved these changes

2021-02-08 12:21 UTC, merged