add docs to dependency-resolver, yarn, pnpm
teambit/bit pull request #3741
Opened 2021-02-04 02:18 UTC by giteden

## Proposed Changes

-
-
-

2021-02-04 10:52 UTC, GiladShoham requested changes

2021-02-04 10:52 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +## Quickstart & configuration
add sections about
1.  authentication
2. proxy configuration

2021-02-08 14:11 UTC, GiladShoham requested changes

2021-02-08 14:21 UTC, GiladShoham requested changes

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +  If the dependencies are external packages or components, it goes on to determine their version and the dependency-type (`dependencies`, `devDependencies`, `peerDependencies`).
Add that it's also calculate the type - component/package
Change the name (type) of dep/dev/peer to lifecycle type

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +          "classnames": "1.0.0"
missing the `dependencies` entry above the classnames

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +          "classnames": "1.0.0"
show an example of using - to remove something / or to remove and add it to another lifecycle

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +        "lodash": "3.0.0"
need to add an example and explanation of preserve property in specific dep

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +Dev dependencies are determined by the type of file that consumes them.
link to devFiles aspect docs, it's a whole aspect itslef

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +Dev dependencies are determined by the type of file that consumes them.
mention that if something is both required in dev file and regular file it will be considered as runtime not a dev

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +The list of file extensions to be considered as development is determined by the various Bit aspects and extensions that are in use. For example, the `@teambit/react/react` environment lists all `*.s
spex => spec ?

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +$ bit install
add diffrences between install in ws and install in capsules

2021-02-08 14:21 UTC, GiladShoham commented on scopes/dependencies/pnpm/pnpm.docs.md
> +> The pnpm aspect uses Bit's deduping algorithm - not pnpm's.
need to explain about this algorithm and link to it here

2021-02-09 23:05 UTC, giteden commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +## Quickstart & configuration
Done.

2021-02-10 10:34 UTC, GiladShoham requested changes

2021-02-10 10:34 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +$ bit install
let's note it aside, and take care of this later

2021-02-10 10:34 UTC, GiladShoham commented on scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
> +##### A proxy can also be set in Bit's global configuration
what about the proxy config from npmrc?
and the order (dep resolver config, npmrc, global config)

2021-02-11 09:35 UTC, merged