feat: pass node-linker to pnpm API
teambit/bit pull request #5220
Opened 2022-01-04 11:52 UTC by zkochan

This should allow to finish #4945

## Proposed Changes

-
-
-

2022-01-04 23:25 UTC, zkochan commented
I tested this on this repository. `bit install`, `bit compile`, `npm run build`, and `bit start` worked.

2022-01-05 09:40 UTC, GiladShoham requested changes

2022-01-05 09:40 UTC, GiladShoham commented on scopes/dependencies/pnpm/pnpm.package-manager.ts
> +        nodeLinker: config.nodeLinker,
I would get this value first from the pnpm config in the workspace.jsonc
to do it, all you need to do is get another argument in the pnpm.main.runtime provider which called config (right after the deps array) - see the dep-resolver.main.runtime.
This config will auto include everything that configured under the pnpm aspect in the ws.jsonc.
If it exists take it from there. only if not take it from the npmrc config.

2022-01-05 18:24 UTC, davidfirst approved these changes

2022-01-05 18:45 UTC, merged