Diagnostic aspect
teambit/bit pull request #5421
Opened 2022-02-17 08:10 UTC by jonatankBIT

## Proposed Changes

- Diagnostic aspect
- Refactored `diagnosticData` to `reports`

2022-02-17 09:34 UTC, GiladShoham requested changes

2022-02-17 09:34 UTC, GiladShoham commented on scopes/harmony/diagnostic/diagnostic.main.runtime.ts
> +  static getBitVersion() {
unifi with https://github.com/teambit/bit/blob/5e5bfd83b0fa9370ad3144e69078f1ee95ab2628/src/bootstrap.ts#L123

2022-02-17 09:36 UTC, GiladShoham requested changes

2022-02-17 09:36 UTC, GiladShoham commented on scopes/harmony/diagnostic/diagnostic.ts
> +  diagnosticFn: () => Object;
add a name and description to the type.
So later on you can easily know what value belongs to what diagnositic

2022-02-20 08:22 UTC, guysaar223 approved these changes

2022-02-20 08:22 UTC, merged