Graphql schema directives
teambit/bit pull request #5533
Opened 2022-03-10 16:23 UTC by jonatankBIT

close #5532 

## Proposed Changes

- Supports filtered directives on graphql.

2022-03-14 20:40 UTC, guysaar223 requested changes

2022-03-14 20:44 UTC, guysaar223 commented
`** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
"resolvers" defined in resolvers, but not in schema

⠹ Starting UI servers for 'dev'` 

@jonatankBIT 
you have that error when starting new scope or workspace
you need to validate that by running a new workspace and start 
`bit init` 
`bit start`

2022-03-15 09:37 UTC, guysaar223 requested changes

2024-01-01 14:07 UTC, GiladShoham commented
already implemented differently

2024-01-01 14:07 UTC, closed without merging