update webpack prerender plugin
teambit/bit pull request #5801
Opened 2022-05-12 17:00 UTC by KutnerUri

## Proposed Changes

- replace `@dreysolano/prerender-spa-plugin` with the up to date `prerender-spa-plugin-next`
- remove `staticDir` (new plugin now respects `outputPath`)
- remove postProcessor (the default behavior works better, and caused problems with `/` route)
- updated options type according to the plugin docs

2022-05-12 23:03 UTC, NitsanCohen770 approved these changes

2022-05-15 16:34 UTC, KutnerUri commented on scopes/react/react/apps/web/plugins/prerender.ts
> +    ...options,
forwarding all options from the consumer.

- staticDir - is no longer needed with the new plugin, as it now respects the webpack output.path
- postProcess - the built in behavior works the same, and covers the '/' route
- server - forwarde
- renderer - using our custom renderer, with v14 support

2022-05-16 08:53 UTC, GiladShoham requested changes

2022-05-16 08:56 UTC, KutnerUri commented on scopes/react/modules/prerenderer-puppeteer/prerenderer-puppeteer.ts
> + * and added types
```suggestion
 * - added types
```

2022-05-16 08:57 UTC, KutnerUri commented on scopes/react/modules/prerenderer-puppeteer/prerenderer-puppeteer.ts
> + * and added types
```suggestion
 * - added types
```

2022-05-16 10:15 UTC, GiladShoham approved these changes

2022-05-16 10:16 UTC, merged