fix(Preview): remove compositions from overview
teambit/bit pull request #7504
Opened 2023-06-06 22:36 UTC by luvkapur

2023-10-16 14:30 UTC, GiladShoham requested changes

2023-10-26 18:03 UTC, davidfirst approved these changes

2023-10-30 15:14 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +  async includesOnlyOverview(component: Component): Promise<boolean> {
rename to get*

2023-10-30 15:14 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +  async useNameParam(component: Component): Promise<boolean> {
rename to get*

2023-10-30 15:15 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    const previewData = this.getPreviewData(component);
read from the data only

2023-10-30 15:15 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    const previewData = this.getPreviewData(component);
read from the data only

2023-10-30 15:29 UTC, GiladShoham requested changes

2023-10-30 15:29 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +      useNameParam: true,
change to support*

2023-10-30 15:29 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    return !!previewData?.useNameParam;
change to support*

2023-10-30 15:29 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    return !!previewData?.onlyOverview;
change to support*

2023-10-30 15:29 UTC, GiladShoham commented on scopes/pipelines/builder/builder.main.runtime.ts
> +      return envData?.inWs && !envData?.lastTaggedEnvHasOnlyOverview;
what if the env is also tagged in the process?

2023-10-31 09:26 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    // if (!this.config.onlyOverview) return false;
Is this commented by purpose?

2024-01-01 10:43 UTC, GiladShoham approved these changes

2024-01-01 10:44 UTC, merged