update templates
teambit/bit pull request #7948
Opened 2023-09-21 23:32 UTC by NitsanCohen770

Update core workspace starters templates to contain basic deps for eslint plugin

2023-09-21 23:38 UTC, NitsanCohen770 commented
This PR is also available on a CR. Let's merge the CR instead please (then I can import the changes to the repo)
https://bit.cloud/teambit/community/~change-requests/update-core-starters

2023-09-22 04:33 UTC, GiladShoham requested changes

2023-09-22 04:33 UTC, GiladShoham commented on scopes/generator/generator/templates/basic/template/files/workspace-config.ts
> +        '@typescript-eslint/eslint-plugin': '5.35.1',
Please change back to 5.62
I've just upgraded it

2023-09-22 04:33 UTC, GiladShoham commented on scopes/generator/generator/templates/starter/files/workspace-config-tpl.ts
> +  const packageManagerDefaultConfig = configParsed['teambit.dependencies/dependency-resolver'];
Rename 
This is not package manager config but deps resolver config

2024-01-04 21:41 UTC, closed without merging