Add a pre-bundle task for preview
teambit/bit pull request #8050
Opened 2023-10-23 08:16 UTC by Jinjiang

## Proposed Changes

-
-
-

2023-10-23 08:26 UTC, GiladShoham requested changes

2023-10-23 08:26 UTC, GiladShoham commented on scopes/preview/preview/preview.main.runtime.tsx
> +    const name = this.workspace?.name || 'workspace';
We need to see what happens on bare scope with this (we just did some special impl for bare scope for the ui pre-bundle. see here - https://github.com/teambit/bit/pull/8028
(but maybe we can find a simpler solution)

2023-10-23 08:26 UTC, GiladShoham commented on scopes/ui-foundation/ui/pre-bundle-preview.task.ts
I think we should move that file to the preview aspect, why is it inside ui aspect?

2023-10-23 08:26 UTC, GiladShoham commented on scopes/ui-foundation/ui/pre-bundle-preview.task.ts
> +  aspectId = 'teambit.ui-foundation/preview';
once moved the file to preview aspect, take the aspect id from the `preview.aspect.ts` file

2023-10-23 08:26 UTC, GiladShoham commented on scopes/ui-foundation/ui/pre-bundle-preview.task.ts
> +      (c) => c.component.id.toStringWithoutVersion() === UIAspect.id
This should be the PreviewAspect.id not ui

2023-10-23 08:26 UTC, GiladShoham commented on scopes/ui-foundation/ui/pre-bundle-preview.ts
> +const ENTRY_CONTENT = `import { Harmony } from "@teambit/harmony";
This file should be auto-generated during the task running

2023-10-23 08:26 UTC, GiladShoham commented on scopes/ui-foundation/ui/ui.main.runtime.ts
> +    this.logger.debug(`pre-build, preview`);
mention something like preview: start or preview: start pre build

2023-10-24 10:37 UTC, Jinjiang commented on scopes/ui-foundation/ui/pre-bundle-preview.task.ts
Because I forked the task from ui and reused a lot of utils there. But I agree with you. I have moved it to preview. Thanks.

2023-11-03 03:57 UTC, Jinjiang commented
Will split this PR into 2 parts.
- pre-bundle-preview task #8097 
- consume the pre-bundle-preview WIP

2023-11-03 03:57 UTC, closed without merging