feat: update dev server managed paths
teambit/bit pull request #8067
Opened 2023-10-26 12:28 UTC by leimonio

## Proposed Changes

Change generated managed paths to explicitly generated ones based on the tartget.

2023-10-26 17:18 UTC, zkochan submitted a review, later dismissed

2023-10-29 09:12 UTC, GiladShoham approved these changes

2023-10-29 09:14 UTC, GiladShoham requested changes

2023-10-29 09:14 UTC, GiladShoham commented on scopes/dependencies/modules/packages-excluder/generate-node-modules-pattern.ts
> +  isPnpmEnabled: boolean;
I think we should make this optional (default true)

2023-10-29 09:14 UTC, GiladShoham commented on scopes/dependencies/modules/packages-excluder/generate-node-modules-pattern.ts
> +  isPnpmEnabled: boolean;
if it's not optional, people might get now type errors if they update the package excluder but not bit

2023-10-30 14:22 UTC, GiladShoham approved these changes

2023-10-30 14:23 UTC, merged